# Generated by Django 3.1.2 on 2020-11-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201113_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='artwork',
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.exhibition'),
        ),
    ]
