# Generated by Django 3.1.2 on 2020-11-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201113_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='exhibition',
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibition',
            field=models.ManyToManyField(null=True, to='app.Exhibition'),
        ),
    ]
