# Generated by Django 3.1.2 on 2020-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201116_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='exhibition',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='artwork',
            field=models.ManyToManyField(null=True, to='app.Artwork'),
        ),
    ]
