# Generated by Django 3.1.2 on 2020-11-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201116_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='exhibition_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.exhibitionhall'),
        ),
    ]
